// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxZVTShrYXMUqeB6eqaNY1iLSx7Lemx8Y',
    appId: '1:444338088045:web:d1a17ac598bec69641b764',
    messagingSenderId: '444338088045',
    projectId: 'chatter-3902e',
    authDomain: 'chatter-3902e.firebaseapp.com',
    storageBucket: 'chatter-3902e.appspot.com',
    measurementId: 'G-9XCMYXGYWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn-4ma60H6A0Yf-U0ENE__fh_Kcs2MMA8',
    appId: '1:444338088045:android:b3f0d5a1df6b40aa41b764',
    messagingSenderId: '444338088045',
    projectId: 'chatter-3902e',
    storageBucket: 'chatter-3902e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY5BkyOdVLdS1wCuqkbkR4g46379SGHAM',
    appId: '1:444338088045:ios:4ef60e315719e2b241b764',
    messagingSenderId: '444338088045',
    projectId: 'chatter-3902e',
    storageBucket: 'chatter-3902e.appspot.com',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY5BkyOdVLdS1wCuqkbkR4g46379SGHAM',
    appId: '1:444338088045:ios:46858ff84596531441b764',
    messagingSenderId: '444338088045',
    projectId: 'chatter-3902e',
    storageBucket: 'chatter-3902e.appspot.com',
    iosBundleId: 'com.example.chatter.RunnerTests',
  );
}
